# Generated by Django 5.2.5 on 2025-08-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('blogs', '0002_alter_comment_options_remove_blog_weather_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherprofile',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_profile', to='blogs.blog'),
        ),
    ]
