# Generated by Django 5.2.5 on 2025-08-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_weatherprofile_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherprofile',
            name='last_temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
