# Generated by Django 5.2.5 on 2025-08-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_weatherprofile_last_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherprofile',
            name='blog',
        ),
    ]
