# Generated by Django 5.2.5 on 2025-08-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_weatherprofile_blog'),
        ('blogs', '0002_alter_comment_options_remove_blog_weather_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='weather_profiles',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='api.weatherprofile'),
        ),
    ]
