# Generated by Django 5.2.5 on 2025-08-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_weatherprofile_blog'),
        ('blogs', '0003_blog_weather_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='weather_profiles',
            field=models.ManyToManyField(blank=True, null=True, related_name='blogs', to='api.weatherprofile'),
        ),
    ]
